--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/webbrowser11/My-first-ts-programs
build-by-default: true
branches:
- main
projects:
  CustomScore:
    path: ""
    icon: icon.png
...
